name: 'record'

on: [ issue_comment ]

jobs:
  record: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          milliseconds: 1000
          agent_url: ${{secrets.AGENT_URL}}
          agent_token: ${{secrets.AGENT_TOKEN}}
          bot_alias: ${{secrets.BOT_ALIAS}}
